add_newline = true

[character]
error_symbol = "!!"

[cmd_duration]
min_time = 5_000

[username]
style_user = "bold green"

[directory]
style = "bold blue"

[time]
disabled = false
style = "dimmed white"
format = '[ $time ]($style) '

[dotnet]
disabled = true

[golang]
disabled = true

prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "cmd_duration",
    "line_break",
    "jobs",
    "character"
]
