add_newline = true
format = """
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$status\
$shell\
$character"""

[character]
success_symbol = ";"
error_symbol = "!!"

[username]
style_user = "bold green"

[directory]
style = "bold blue"

[time]
disabled = false
style = "dimmed white"
format = '[ $time ]($style) '

[git_status]
disabled = true

[dotnet]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

