[".local/zinit"]
type = "archive"
url = "https://github.com/zdharma-continuum/zinit/archive/main.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".zsh-plugins/zsh-autosuggestions"]
type = "archive"
url = "https://github.com/zsh-users/zsh-autosuggestions/archive/refs/tags/v0.7.0.tar.gz"
exact = true
stripComponents = 1
